---
sudo: false
language: ruby
cache: bundler
dist: trusty
env:
  - PUPPET_VERSION="~> 4.10.0"
matrix:
  include:
  - rvm: 2.1.9
    bundler_args: --without system_tests release
    env: PUPPET_VERSION="~> 4.0" CHECK=test_with_coveralls PARALLEL_TEST_PROCESSORS=12
  - rvm: 2.4.3
    bundler_args: --without system_tests release
    env: PUPPET_VERSION="~> 4.0" CHECK=rubocop
  - rvm: 2.4.3
    bundler_args: --without system_tests release
    env: PUPPET_VERSION="~> 4.0" CHECK=build DEPLOY_TO_FORGE=yes
  - rvm: 2.4.3
    bundler_args: --without release
    dist: trusty
    env: PUPPET_INSTALL_TYPE=agent BEAKER_debug=true BEAKER_set=docker/ubuntu-14.04 CHECK=beaker
    services: docker
    sudo: required
  - rvm: 2.4.3
    bundler_args: --without release
    dist: trusty
    env: PUPPET_INSTALL_TYPE=agent BEAKER_debug=true BEAKER_set=docker/ubuntu-16.04 CHECK=beaker
    services: docker
    sudo: required
  - rvm: 2.4.3
    bundler_args: --without release
    dist: trusty
    env: PUPPET_INSTALL_TYPE=agent BEAKER_debug=true BEAKER_set=docker/centos-7 CHECK=beaker
    services: docker
    sudo: required
  allow_failures:
    - env: PUPPET_INSTALL_TYPE=agent BEAKER_debug=true BEAKER_set=docker/centos-7 CHECK=beaker
    - env: PUPPET_INSTALL_TYPE=agent BEAKER_debug=true BEAKER_set=docker/ubuntu-16.04 CHECK=beaker
branches:
  only:
  - master
  - /^v\d/
notifications:
  email: false
